version: '3.8'

services:
  php:
    build: .  
    container_name: email_sync_php
    volumes:
      - ./:/app   
    command: php -S 0.0.0.0:4300
    ports:
      - "4300:4300"  

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  composer:
    image: composer:latest
    container_name: email_sync_composer
    volumes:
      - ./:/app   
    working_dir: /app
    command: install --ignore-platform-reqs

